# Variables and Types

## Topics:

* More about Jupyter notebooks
* Variables: integers, floating-point numbers (decimal), strings (text)
* Numerical operations
* Coercion
* Strings: indexing, special characters, formatting, input
---
## Jupyter notebook shortcuts
You can add a new block by clicking the **+** sign on the toolbar or by typing `ESC` and then `b` (for new cell below) or `a` (for new cell above).

You can change the type of block in the dropdown menu in the toolbar, or by typing `ESC` and `m` for Markdown or `y` for Code.

To run a cell, you can click run on the toolbar, or hit `shift + return` (`command + return` if you're on a Mac, and maybe `CTRL + return` for some people)

## Introduction to Python
Let's do the first thing every beginner coder does when they start their programming journey--print hello world.

In [1]:
print('hello world')

hello world



This bit of code tells python to use the `print` function to output the string 'hello world'. Of course, you can print a variety of data types in python: strings like what we just did, integers, floats, etc.
The function `type` tells you what is the data type you gave it:

In [2]:
print('hello world')
print(type('hello world'))

hello world
<class 'str'>

**TO DO:** Print the type of `1` and `1.0` in the cells below:

In [3]:
print(1)

1

In [4]:
print(1.0)

1.0

Here we see 3 different types of data:
* 'str': strings are indicated by quotation marks, regardless of what's inside the quotations.
* 'int': integers are indicated by numbers with no decimals
* 'float': floats are indicated by numbers with decimals (we'll go over the importance soon)

**TO DO:** What happens if we put a number in quotation marks? Check the type of `'1'` in the cell below:

**TO DO:** What if we forget to add quotation marks around strings? Check the type of `hello world` (without quotes) in the cell below:

The integer, 1, becomes a string when it has quotes around it, and the string 'hello world' yields an error. This is because words without quotation marks around them are understood by Python as variable names (more below).

### String quotation marks

String quotation marks can be single, double or triple. For a cleaner code, we generally use single quotes in this bootcamp, and we suggest you do too. But you can use whichever you prefer.

If you want your string to contain double quotes, it's a good idea to surround it with **single quotes**:

In [5]:
print ('She said: "Hello!"')

She said: "Hello!"

If you want your string to contain single quotes, it's a good idea to surround it with **double quotes**:

In [6]:
print ("This is a single quote: '")

This is a single quote: '

The advantage of **triple quotes** is that they can take multiple lines (but later we'll see there are other ways of doing this).

In [ ]:
print ('''Here is
a string 
that takes
four lines. This would break with single or double quotes. Try it if you don't trust me. ''')

## Assigning Variables
Variables are simply representations of the data that you want to work with--Just like how we understand the letters in the equation F = ma to be representations of numbers corresponding to force, mass, and acceleration. To create a variable, you write out your variable name, an "=" sign, and then what you want it to represent. Spaces around the equal sign are optional but encouraged for code readability.

**TO DO:** In the cell below, create a variable called gradStudent, and assign the new variable your name as a string.

Example: 
```Python
gradStudent = 'Tal'
```

Then, print the variable and its type.

<span style="color:red">AT THIS POINT, INTRODUCE THE CONCEPT OF SCOPE WITHIN JUPYTER. EXPLICITLY TELL THEM ANY VARIABLE MADE IN A CODE-BLOCK CAN BE USED BEYOND THIS. THIS MIGHT GET CONFUSING TO THEM WHEN YOU GET TO FUNCTIONS AND SCOPE IN 1.2.2 --LUCAS </span>.

In [ ]:
age = 22

print(age)
print(type(age))

In [ ]:
grandeCoffee = 2.45

print(grandeCoffee)
print(type(grandeCoffee))

Like in math, it's easy to use variables to keep track of values instead of having numbers all over the place. 

**TO DO:** In the cell below, print the result of the `force` calculation:

In [ ]:
mass         = 237.0
acceleration = 9.81
force = mass*acceleration

The result of an operation can be set to a variable. In the simple, above case, the variable "force" is defined by the operation mass times acceleration.

## Numerical operations on Integers
Math with integers works the same way all non-decimal math is done. All integer arithmetic will yield integer results if only integers are used.

In [ ]:
myMoney   = 23 # in dollars
yourMoney = 31
pizzaCost = 5

In [ ]:
print('How much do we have if we pooled our money together?')
print(myMoney + yourMoney)
print(type(myMoney + yourMoney))

How much do we have if we pooled our money together?
54
<class 'int'>

**TO DO:** Print the answer to the questions below:

In [ ]:
print('How much more money do you have than I do?')

How much more money do you have than I do?

**Multiplication** is indicated with an asterisk "*"

In [ ]:
print('How much do you have if you double your money?')

And doing **exponents** requires two asterisks "**"

In [ ]:
print('What if you want to square it?')

Next, there are two different **division** operators:

In [ ]:
print('How many pizzas can I buy?')
print(myMoney/pizzaCost)

How many pizzas can I buy?
4.6

In [ ]:
print(myMoney//pizzaCost)

4

2 important nuances here. Division is indicated by a slash "/" sign. Also, notice that 23/5 does yield a decimal value. Integer division will yield only the integer portion of the quotient if you're in python 2, in which case, you have to make sure at least one of the values are coerced into a __float__. However, you can get the integer portion of a positive number in python 3 using the __floor__ function "//".

You can get the **remainder** of a division by using the percent "%" sign instead of the division sign. This "%" is called **mod**.

**TO DO :** In the cell below, print how much money you have left after buying 4 pizzas using `%`

In [ ]:
print('How much money do I have left over after buying 4 pizzas?')

If the order of operations is ambiguous, Python works with the standard conventions, but it is always better to be explicit (by using parentheses).

In [ ]:
print(2+4*3)
print(2+(4*3))
print((2+4)*3)

## Back to strings: indexing, special characters, formatting, and inputs

## Numerical operations on Strings
You can perform basic numerical operations (addition multiplication) on strings and the outcome is a visual representation of the math!

In [ ]:
stringA = 'aca'
stringB = 'bdb'

print(stringA)
print(stringB)

**TO DO:** In the cells below, print the result of the numerical operations on `stringA` and `stringB`.

In [ ]:
print('stringA + stringB is')

In [ ]:
print('stringA times 3 is')

In [ ]:
print('What happens if you multiply a string by a float?')
#print(stringA * 3.0)

# by the way, lines starting with the pound sign (#)
# makes them comments, ignored by the interpreter

As we see here, adding strings basically **concatenate** them together and multplying strings by an integer (it doesn't work with floats) will yield the same string repeated over and over again.

Also, note the # sign, which indicates lines that are ignored by python. As you write your own code, it's good practice to use **commented lines** to describe what bits of code do and how they do it.

## Coercion
You can force number types to become another type using the int(), float(), and str() functions. This is also called typecasting.

In [ ]:
# Note: You can print multiple things separating them by a comma
print(type(1), type(float(1)), type(str(1)))

In [ ]:
print(type(1.), type(int(1.)), type(str(1.)))

- int() forces values to be an integer. Floats will be rounded down to the nearest integer.
- float() forces values to become a float
- str() forces values to become a string

*Questions?*

## Indexing
Python has this thing called "indexing," a way to access data. Indexing enables you to pull specific parts of strings or lists (to be discussed in future lectures).

We index by adding square brackets "[]" right after a string. **Python indexing starts with 0** instead of 1.

In [ ]:
someString = 'abcdefghij'

```
someString:  a b c d e f g h i j
Index:       0 1 2 3 4 5 6 7 8 9
```

**TO DO:** In the cell below, print the first letter of the string `someString`, using [0] as the index.

In [ ]:
print('what are the other letters of someString?')

print(someString[1])
print(someString[2])
print(someString[3])
print(someString[4])
print(someString[5])
print(someString[6])
print(someString[7])
print(someString[8])
print(someString[9])

You can also store these as variables!

In [ ]:
var1 = someString[1]
var2 = someString[2]
var3 = someString[3]

print(var1)
print(var2)
print(var3)

print(var1 + var3 + var2)

**TO DO:** In the cell below, try using an index that is equal to or larger than the length of the string (which is 10).

In [ ]:
print('What if we use an index larger than the length of the string?')
#print(someString[ ])

**TO DO:** In the cell below, try using a negative index.

In [ ]:
print('What if we use negative values?')
#print(someString[ ])

Using negative values counts backwards instead!
```
String:           a  b  c  d  e  f  g  h  i  j
Negative Index: -10 -9 -8 -7 -6 -5 -4 -3 -2 -1  
```

## String slicing

We'll continue to use this string as our example:
```
String:  a b c d e f g h i j
Index:   0 1 2 3 4 5 6 7 8 9
```

If you want to extract a sequence of characters from a string, instead of a single character, you can do this by using the following syntax:

In [ ]:
print(someString[1:5])

In this case, the first number represents the first letter to print all the way up to **but not including** the letter in the position of the second number.
```
String:  a b c d e f g h i j
Slice:     1 2 3 4|5 
```

There's one more indexing notation, in which there's a third number, which tells us how many units to count by:

In [ ]:
print(someString[0:5:2])

```
String:  a b c d e f g h i j
Slice:   0 - 2 - 4|5 
```

To count backwards, make sure to have a negative number as the third indexing value. (Also, if you don't put any index in the first or second field, the whole string is considered):

In [ ]:
print(someString[::-2])

```
String:    a b c d e f g h i j
Slice:     - 1 - 3 - 5 - 7 - 9
Direction: < < < < < < < < < <
```

If you want to count backwards within a subset of values in the string, make sure the first number is larger than the second while indexing:

In [ ]:
print(someString[7:2:-1])

```
String:    a b c d e f g h i j
Slice:         2|3 4 5 6 7
Direction:     < < < < < <
```


## Special Characters
There are special characters than can be used in strings to do some interesting things. They're generally indicated with a backslash and some letter. The most common ones for string formatting I've seen are `\t` and `\n`, which correspond to **tabs** and **newlines**:

<span style="color:red">DURING THIS SECTION, WE COULD FORMALLY INTRODUCE THE FASTA-FILE FORMAT, AND DEMONSTRATE HOW THIS FORMAT USES ESCAPE CHARACTERS AS NEW-LINES. WE SHOULD ALSO SHOW A BED-FILE, FOR EXAMPLE, TO HIGHLIGHT OF THE TAB ESCAPE CHARACTER IS USED. FASTA-FILES WILL DEFINITELY REAPPEAR, SO FORMALLYING INTRODUCING IT IS A MUST. BEDFILES ARE PRETTY SIMPLE TOO, ALTHOUGH UNSURE IF WE'LL USE THEM AGAIN IN FUTURE LECTURES. --LUCAS </span>.

In [ ]:
s = 'some\thing is missing'
print(s)
s2 = "somethi\ng is broken"
print(s2)
s3 = 'something th\at will drive you b\an\an\as'
print(s3)

In [ ]:
s4 = r'\a solu\tio\n'
print(s4)
 
s5 = '\\another solu\\tio\\n'
print(s5)

This ugly (and possibly loud, if your sound is working properly) mess is caused by escape characters. In python strings, several special characters (full list here: https://docs.python.org/2/reference/lexical_analysis.html#string-literals) can be preceded by a backslash (\) to produce special output, such as a tab (\t) newline (\n) or even a bell noise (\a).

You may think of the backslash as a character that tells the computer to treat the next character as something other than the default. 'n' becomes a new line when preceded by a backslash, 't' becomes as tab, etc. If you want to include an actual backslash in your string, then this logic still stands: the default behavior of a backslash is being a special character, if we want to change that behavior - we put a backslash before it (So '\\' would print as '\').

Sometimes when dealing with paths or specific formats, escaping each special character can be a lot of work, which is why python has a "raw string" (defined as r"" instead of the normal ""). Then the assumption is that all characters in the string are literal characters, with the obvious exception of the close quotes.

If you do use raw strings, watch out for two catches:
* You must still escape quotes you want to appear inside the string (single quotes or double quotes, depending on how you defined the string)
* The last character of the string cannot be a backslash, since this will escape the closing quote.
Color coding from synthax highlighting will help you notice the problems:

In [ ]:
#s7 = r'this is bad because there is no space after the slash\'
s7 = r'but this is okay\ '
print(s7)

## Formatting
We've learned about strings and variables, but how can we put them together? This is where formatting comes into play, where we can combine them together on a line. To format strings or, in other words, to be able to place variables within a string, just place curly braces {} where you'd like variables to appear; then use .format() and type in a list of variables to input. Variables that are not strings will be coerced to string type.

If you put too many variables in the .format() list, the excess will not be included in the string.

In [ ]:
pet = 'cat'
howMany = 13

print('I have a {}, {} of them. Does this make me a hoarder?' .format(pet, howMany))

You can also reference the same variables more than once by their index in the parentheses.

In [ ]:
pet = 'cat'
howMany = 13

sentence = 'I have a {0}, {1} of them. Does this make me a {0} hoarder?'
print(sentence.format(pet, howMany))

String formatting is very useful when you have a template string that you want to fill in with different variables each time. For example:

In [ ]:
phonebook = '{0}\n{2}-{1}\n'

print(phonebook.format('Dat', 8912345, 511))
print(phonebook.format('Debora',1234567, 510))
print(phonebook.format('Diana', 6789123, 512))

**TO DO:** Change the phonebook template string above so that you have phones separated from names by a tab, no newline between entries, and a space between area code and phone.

You can also name the variables that you are using in string formatting:

In [ ]:
shoplist = '{howmany}\t{item}'
print(shoplist.format(howmany=1, item='onions'))
print(shoplist.format(howmany=2, item='tomatoes'))
print(shoplist.format(howmany=6, item='avocados'))
print(shoplist.format(howmany=1, item='lime'))
print(shoplist.format(howmany='1 bunch', item='cilantro'))

**TO DO:** In the cell below, change the phonebook example again, using the following template: `phonebook = '{name}\t{code}{phone}'`

In [ ]:
phonebook = '{name}\t{code}{phone}'
print(phonebook.format('Dat',    8912345, 511))
print(phonebook.format('Debora', 1234567, 510))
print(phonebook.format('Diana',  6789123, 512))

## Input

This will seem random, but it's something fun to be able to do at this stage of coding. This Python function will print a message that will require you to type something in and then storing it as a string. This sounds more complicated than it really is. The following shows the format of how it's done.

In [ ]:
name = input("what's your name? ")
print(name)

Notice that everything is read in as a string, even numbers. Remember that if you want numbers to be an int or a float, just use coercion with int() and float() functions

In [ ]:
age = input("How old are you? ")
print(age)
print(type(age))

**Note**: if you run a Jupyter notebook cell that contains an `input` function but you don't give it any input, the notebook will get stuck there waiting for input and you won't be able to run other cells. You can see this is hapenning if there is a `In [*]:` on the left of the cell, and a dark circle on the top right corner of your notebook, beside "Python 3". You can fix this by either giving some input to the input function, or by going to Kernel > Interrupt.

<span style="color:red">IN TERMS OF HOW THIS SET OF EXERCISES COULD BE CHANGED, I THINK IT MAY BE USEFUL TO CHANGE THIS INTO A SINGLE EXERCISE ON CORRECTING SOME ERROR-RIDDLED CODE? AT THIS STAGE, THE STUDENTS SHOULD BE AWARE ERRORS EXIST, ALTHOUGH LIKELY NOT READING THE ERROR MESSAGES THEMSELVES. THAT'S OKAY FOR AN EXCERCISE LIKE THIS AS THE PRIMARY OBJECTIVE IS FOR THEM TO SEE ON THE CODE THE SYNTAX MISTAKES. YOU COULD EITHER DO THE EXAMPLES AS SEPARATE ERROR-RIDDLED-CODE-BLOCKS AND HAVE THEM CORRECT THE SYNTAX, OR ONE LARGE CODE BLOCK. I THINK HAVING MULTIPLE WOULD BE BEST TO INCREASE READIBILITY AND LIMIT SCOPE DURING EACH ATTEMPT AT CORRECTING THE SYNTAX. --LUCAS </span>.

# Exercises

## Required

### 1) Ratio

Ask the user for two numbers (use the `input` function twice, creating a separate variable to store each number). Print out their ratio.

### 2) Age
Write a script that will ask for someone's age and print out the year they're born in. The final output should be in the format: You are "age" years old, so you were born in "year".

### 3) Sequence formatting
Here is a string:

In [ ]:
fasta = '>gene1ACTAGCTACAGTTCGCNAGC>gene2TCGATCNATCGATNGTCGAT'
print(fasta)

>gene1ACTAGCTACAGTTCGCNAGC>gene2TCGATCNATCGATNGTCGAT

Can you add special characters such that this **single** string will print like an actual fasta file, with 10 nucleotides per line? 

The result of printing your string should look like this:

    >gene1
    ACTAGCTACA
    GTTCGCNAGC
    >gene2
    TCGATCNATC
    GATNGTCGAT'

### 4) Sequence slicing
Here is the sequence of gene1 above, now attributed to a separate variable:

In [ ]:
gene1 = 'ACTAGCTACAGTTCGCNAGC'

Write a code that will ask 2 questions (use the input function). The first question will ask for a number between 0 and 10 while the second question will ask for a number betwen 11 and 20. Index the variable consisting of the gene1 sequence ranging from the first number to the second. What is the result? It should look something like:

```
What is the first number? 4
What is the second number? 15
GCTACAGTTCG
```

## Extra practice

### 1) Sum and Mean

Read five numbers in (from user input). Print out their sum and mean.

### 2) Budget
Write a code that asks for how much money you have and also how much something costs (e.g. a pencil). Calculate how many of these things you can buy and how much money you would have left over.

## Challenge

Ask the user for a gene sequence. Print out the codons (triplets of DNA letters) vertically, like in the example below. 

If the user input is:

    CGACTCGATGCTATCGCGATCGC

your code should print it out as:

```
CCGGAGAG
GTACTCTC
ACTTCGC
```

**Extra challenge** if you can use a single print statement.